### ISSUE TITLE
Color settings don't seem to change color much?

### ISSUE THREAD

**Issue by seebs** [digitallyserviced/semanticolor#31]
Changing the number of colors changes color choices quite a bit, although low N produce a very noticeable red-orange tendencies, rather than evenly-spaced colors throughout the hue range but with more space between them. I can't detect any impact at all, though, from changes to luminosity, saturation (which is misspelled "stauration" in its explanatory text), or fade.

**Comment by seebs** [comment]
Update: This may be a UI glitch. Specifically, it looks like the color selection changes with changing the number of hues, but the actual hues are updated only if I change "syntax theme" in the theme part of settings.

**Comment by sharedprophet** [comment]
You may need to reload the window to see correct results after changing color settings.

**Comment by seebs** [comment]
Yeah, reloading window, changing "theme", or restarting the app all seem to work. I think I just assumed it would take effect right away, because there was a message about regenerating colors.

I am still a bit unclear on the distinction between "fade" and "saturation", they both seem to make colors less-strong? My speculation is that saturation/luminosity are determining a set of colors, and fade is controlling interaction between those colors and the theme's default colors, but I'm honestly not sure.

**Comment by sharedprophet** [comment]
Yes, that’s correct. Saturation and luminosity determine “vividness” of colors. If you’ve ever used Photoshop or a similar app, reducing saturation of an image moves it towards grayscale. Luminosity is brightness.

“Fade” is used after generating the initial color values to blend the colors with the theme you’ve chosen. It determines the mix of the color value and the theme’s background color.
