### ISSUE TITLE
shadowed variables should get new colors

### ISSUE THREAD

**Issue by seebs** [digitallyserviced/semanticolor#32]
```
func main() {
	var1 := "hello"
	for  {
		var1 := "foo"
	}
}
```

one of the best use cases for semantic coloring would be realizing that these are two different things named `var1`.

**Comment by sharedprophet** [comment]
Currently semanticolor doesn't actually know about the semantics (I know, I know) of your program. If it could take advantage of tree-sitter grammars (I have an issue open for what we need in order to support them: https://github.com/atom/atom/issues/19151), we could do something like this...

**Comment by sharedprophet** [comment]
After further investigation I don't think this is ever likely to be possible. The problem is that scoping rules can be different between languages and this is a generic solution that works for any language grammar...
