### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by C-Bouthoorn** [digitallyserviced/semanticolor#35]
First of all thanks for this amazing package. I've been using it for a while now and I feel like it upped my production quite a bit. I wondered if you could also add support for Rust now that it's part of the Core Atom package. Thanks :blush:

**Comment by sharedprophet** [comment]
The core Rust grammar is a tree-sitter grammar, so this will come for free once we get Tree-Sitter support. (Need a resolution to atom/atom#19151)

**Comment by C-Bouthoorn** [comment]
I see. Then I'll watch that thread instead and close this one. Thanks again :)
