### ISSUE TITLE
Not available for TypeScript on latest  Atom

### ISSUE THREAD

**Issue by ocoka** [digitallyserviced/semanticolor#36]
On latest Atom (1.45.0) TypeScript no more present in list of available languages to highlight

**Comment by sharedprophet** [comment]
Sorry, it's my fault. It is fixed by [this PR](https://github.com/atom/language-typescript/pull/44) but I haven't been able to convince them to merge it. :(

**Comment by ocoka** [comment]
Thank's for fast answer, as I understand that's all linked with new tree-sitter grammar  ... and TextMate grammar was abandomed

**Comment by sharedprophet** [comment]
Yeah. I have [another PR](https://github.com/atom/atom/pull/20212) to make it possible for Semanticolor to support Tree-Sitter grammars, but haven't been able to get any response on that one, either...

**Comment by sharedprophet** [comment]
Atom 1.51 finally integrated the fix for this.
